-- CREATE TABLE accounts (
--   id VARCHAR(255) NOT NULL,
--   name VARCHAR(255) NOT NULL,
--   email VARCHAR(255) NOT NULL,
--   picture VARCHAR(255) NOT NULL,
--   PRIMARY KEY (id)
-- );

-- CREATE TABLE recipes (
--   id INT NOT NULL AUTO_INCREMENT,
--   creatorId VARCHAR(255) NOT NULL,
--   title VARCHAR(255) NOT NULL,
--   description VARCHAR(255) NOT NULL,
--   PRIMARY KEY (id),
--   FOREIGN KEY (creatorId)
--     REFERENCES accounts (id)
--     ON DELETE CASCADE
-- );

-- CREATE TABLE ingredients (
--   id INT NOT NULL AUTO_INCREMENT,
--   creatorId VARCHAR(255) NOT NULL,
--   title VARCHAR(255) NOT NULL,
--   amount VARCHAR(255) NOT NULL,
--   notes VARCHAR(255) NOT NULL,
--   recipeId INT NOT NULL,
--   PRIMARY KEY (id),
--   FOREIGN KEY (recipeId)
--     REFERENCES recipes (id)
--     ON DELETE CASCADE
-- );

-- INSERT INTO recipes
-- (id, creatorId, title, description)
-- VALUES
-- ("81e3908a-3997-4f25-bb36-b8d38060cde4", "biscuits", "Good ol' Country Biscuits.");

-- INSERT INTO ingredients
-- (creatorId, title, amount, notes, recipeId)
-- VALUES
-- ("81e3908a-3997-4f25-bb36-b8d38060cde4", "white flour", "2 cups", "sift the flour before adding to mixing bowl.", "1")